apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: quay.io/acend/example-web-python
        command: ["curl", "https://acend.ch"]
      restartPolicy: Never
  backoffLimit: 0
